favicon: null
name: Marco Ng
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.375
  brandStrength: 0
  rhythmicContrast: 0.75
  brandColors:
    - '#304B7F'
    - '#4167AB'
    - '#6FA2E1'
    - '#78759B'
  lightness: 0.5
typography_spectrum: 0.1218638
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8369176
analytics:
  twitter: null
  google: null
  facebook: null
