name: Marco Ng
favicon: null
layout_spectrum: 0
typography_spectrum: 0.63588
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Marco Ng
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a2aebc'
    - '#0b0f0e'
    - '#2f363c'
    - '#7c6d5a'
    - '#edc47d'
  brandStrength: 0.75
  lightness: 0.1765710974577814
  saturation: 0.4616203063633293
  rhythmicContrast: 0.02842635987326503
purpose: []
