name: Marco Ng
favicon: null
layout_spectrum: 0.8709889221936464
typography_spectrum: 0.7373988879844546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6843420905061066
  lightness: 0.17657109745778143
  saturation: 0.4616203063633293
  rhythmicContrast: 0.028426359873265028
purpose: []
